### ISSUE TITLE
Angular 10

### ISSUE THREAD

**Issue by teocto** [regulaforensics/DocumentReader-web-js-client#13]
Is it compatible with angular 10?

**Comment by hotibolshe** [comment]
Yes
The client doesn't depend on any kind of framework and can be used with plain javascript/typescript

**Comment by teocto** [comment]
Could you give an example of signalR connection? I read whole documentation. Nevertheless, I cannot establish SignalR websocket connection.

**Comment by ikliashchou** [comment]
What exactly you are trying to achieve? Why at all you might need signalR while this service has synchronous REST interface?
Please provide more details. You may contact us at support@regulaforensics.com for specific details on our other products usage.

**Comment by teocto** [comment]
I need to get run device, scan document, then get document number then close device connection. But it doesn't make sense to me how to do it with REST. I have read documentation, but I found out only how to get document number. Now I want to be able to connect to device, and scan document, but I don't know what requests I have to do. I've already contact support, but they only redirect me to documentation.

**Comment by hleb-albau** [comment]
closed as not related to current repo
